@Task_HostAddress = http://localhost:5065

GET {{Task_HostAddress}}/offices/
Accept: application/json

###

// Make sure id is a valid office id. Example: 0f4eac82-7f2b-4447-9a9a-5385ad44a809
GET {{Task_HostAddress}}/offices/{id}
Accept: application/json

###
